workflows:
  android-release:
    name: Pocket Android Release
    max_build_duration: 120
    instance_type: mac_mini_m2

    environment:
      java: 21

    cache:
      cache_paths:
        - ~/.gradle/caches
        - ~/.gradle/wrapper

    scripts:
      - name: Set Android SDK
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"

      - name: Grant Permission
        script: |
          chmod +x gradlew

      - name: Clean Project
        script: |
          ./gradlew clean

      - name: Build APK
        script: |
          ./gradlew assembleRelease

      - name: Build AAB
        script: |
          ./gradlew bundleRelease

    artifacts:
      - app/build/outputs/**/*.apk
      - app/build/outputs/**/*.aab
      - build/**/outputs/**/*.apk
      - build/**/outputs/**/*.aab

    publishing:
      email:
        recipients:
          - prince.ar.abdur.rahman2008@gmail.com
        notify:
          success: true
          failure: true
