workflows:
  android-build:
    name: PocketPal AI APK

    environment:
      flutter: stable
      java: 17

    cache:
      cache_paths:
        - ~/.pub-cache
        - ~/.gradle

    scripts:
      - name: Show files (debug)
        script: ls -la

      - name: Get dependencies
        script: flutter pub get

      - name: Clean build
        script: flutter clean

      - name: Build APK
        script: flutter build apk --release

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk