workflows:
android-build:
name: Pocket React Native APK

environment:
  java: 17

cache:
  cache_paths:
    - ~/.gradle/caches
    - ~/.gradle/wrapper
    - ~/.npm
    - ~/.yarn

scripts:
  - name: Install dependencies
    script: |
      yarn install

  - name: Build APK
    script: |
      cd android
      chmod +x gradlew
      ./gradlew assembleRelease

artifacts:
  - android/app/build/outputs/apk/release/*.apk
  - android/app/build/outputs/**/*.aab
